FROM node:20 AS build

RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

RUN npm install typescript -g

COPY ./package.json .

COPY ./tsconfig.json .

COPY ./.eslintrc.js .

RUN npm install --no-optional

COPY ./src ./src

RUN ["npm", "run", "build"]

RUN chown -R root:root /home/node/app/dist

FROM node:20

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --from=build /home/node/app/dist ./dist

COPY --from=build /home/node/app/package.json ./

COPY --from=build /home/node/app/src/docs ./src/docs

RUN npm install --only=production

EXPOSE 2000

ARG NODE=production

ENV NODE_ENV ${NODE}

ARG PORT=2000

ENV SERVER_PORT ${PORT}

CMD [ "node", "dist/index.js" ]