version: '3'
services:
  mongodbdev:
    container_name: mongodbdev
    image: mongo
    ports:
      - '27017:27017'
    expose:
      - 27017
    volumes:
      - dbdata:/data/db
  jsguruapp:
    container_name: jsguruapp
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
    expose:
      - '2000'
    ports:
      - '2000:2000'
    command: npm run start
volumes:
  dbdata: